BHoM/Dynamo_UI

Dynamo_Engine/Convert/ToDesignScript.cs
Temporary conversion of PlanarSurface (to ICurve).
=> Dynamo_Toolkit - Issue133 - PlanarSurface Conversion

.github/ISSUE_TEMPLATE/api_changed.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/compliance.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/test_script.md
=> Dynamo_Toolkit - #149 - Issue Templates

docs/PULL_REQUEST_TEMPLATE.md
Default Pull Request template added to Dynamo Toolkit
=> Dynamo_Toolkit - #151 - Pull Request Template

Dynamo_Engine/Properties/AssemblyInfo.cs, Dynamo_UI/Properties/AssemblyInfo.cs, Methods_Dynamo/Properties/AssemblyInfo.cs
Fixes #148 
N/A
- Changed Assembly File Version
=> Dynamo_Toolkit: Assembly File Version update

Dynamo_Engine/Convert/ToBHoM.cs, Dynamo_Engine/Convert/ToDesignScript.cs, Dynamo_Engine/Objects/DataAccessor_Dynamo.cs
Closes #153 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Dynamo_Toolkit/Dynamo_Toolkit-ConvertForNurbsCurve?csf=1&e=wpSaYD
- Add `Convert.ToBHoM(NurbsSurface)`
- Add `Convert.ToDesignScript(NurbsSurface)`
=> Dynamo_Toolkit: implement convert for NurbsSurface

Dynamo_Engine/Convert/ToBHoM.cs, Dynamo_Engine/Convert/ToDesignScript.cs
Co-Authored-By: Erik Narhi <erik.narhi@burohappold.com>
N/A
Closes #153 
Pull and Push BHoM NurbSurface did not work
as per #156 
NurbSurface ToBHoM and ToDesignScript modified
N/A
=> Dynamo_Toolkit - #153 - NurbSurfaces Fix

Methods_Dynamo/CRUD/Move.cs
https://github.com/BHoM/BHoM_Adapter/pull/128
Refactor to follow https://github.com/BHoM/BHoM_Adapter/pull/128
* Renamed the method called from the "Move" component from `PullTo` to `Move`
* Added `config` parameter in the Move component so that user can input both `pullConfig` and `pushConfig`
=> Modify Move component to reflect changes in BHoM_Adapter

Dynamo_Engine/Dynamo_Engine.csproj, Dynamo_UI/Dynamo_UI.csproj, Methods_Dynamo/Methods_Dynamo.csproj
Closes #166 
Copy Local for all references set to False
N/A
- 'Dynamo_Engine.csproj' - all Copy Local set to false
- 'Dynamo_UI.csproj' - all Copy Local set to false
- 'Methods_Dynamo.csproj' - all Copy Local set to false
N/A
=> Dynamo_Toolkit - #166 - False Copy Local

Dynamo_Engine/Properties/AssemblyInfo.cs, Dynamo_UI/Properties/AssemblyInfo.cs, Methods_Dynamo/Properties/AssemblyInfo.cs
N/A
Closes #168
N/A
- 'AssemblyInfo.cs' for Dynamo_Engine updated with the latest AssemblyFileVersion 
- 'AssemblyInfo.cs' for Dynamo_UI updated with the latest AssemblyFileVersion 
- 'AssemblyInfo.cs' for Methods_Dynamo updated with the latest AssemblyFileVersion 
N/A
=> Update AssemblyFileVersion to 2.4.0.0

Dynamo_UI/New/Views/Engine/Explode.cs
Closes #132 
I didn't have the original script shown on the issue so I used this instead: 
The explode component should update the first time you connect the input now.
=> Fix explode of List of Lists

Dynamo_Engine/Properties/AssemblyInfo.cs, Dynamo_UI/Properties/AssemblyInfo.cs, Methods_Dynamo/Properties/AssemblyInfo.cs
N/A
Closes #174 
N/A
- `AssemblyInfo.cs` files for all projects updated with new version
N/A
=> Assembly Version Updated

Dynamo_UI/New/Views/oM/CreateObject.cs
https://github.com/BHoM/BHoM_UI/pull/147
See https://github.com/BHoM/BHoM_UI/pull/147 for more details
=> Update to the new version of the CreateObject component

Dynamo_UI/New/Components/oM/CreateObject.cs, Dynamo_UI/New/Templates/CallerView.cs, Dynamo_UI/New/Views/oM/CreateObject.cs
https://github.com/BHoM/BHoM_UI/pull/152
See https://github.com/BHoM/BHoM_UI/pull/152 for more details
=> Refine the CreateObject component

Dynamo_Engine/Properties/AssemblyInfo.cs, Dynamo_UI/Properties/AssemblyInfo.cs
=> Update assembly file version to 3.1.0.0

Dynamo_UI/Components/Adapter/Delete.cs, Dynamo_UI/Global/GlobalSearch.cs
BHoM/BHoM_Engine#1371
BHoM/BHoM_Adapter#164
https://github.com/BHoM/BHoM_UI/pull/167
Closes #187 
- Delete adapter action component renamed to "Remove"
=> Aligning with changes in BHoMAdapter Refactoring Level 04

Dynamo13/Dynamo_Engine/Dynamo13_Engine.csproj, Dynamo20/Dynamo_Engine/Dynamo20_Engine.csproj
https://github.com/BHoM/BHoM/pull/704
https://github.com/BHoM/BHoM_Engine/pull/1484
https://github.com/BHoM/BHoM_Adapter/pull/193
Closes #212 
Adds references to Dimensional_oM where necessary and 'using' statments where that is necessary 
to comply with the changes in https://github.com/BHoM/BHoM/pull/704
=> Update IElement references with the Dimensional_oM

Dynamo13/Dynamo_Engine/Convert/FromDesignScript.cs, Dynamo13/Dynamo_Engine/Convert/ToBHoM.cs, Dynamo13/Dynamo_Engine/Convert/ToTargetType.cs, Dynamo13/Dynamo_Engine/Dynamo13_Engine.csproj, Dynamo13/Dynamo_Engine/Objects/DataAccessor_Dynamo.cs, Dynamo13/Dynamo_Engine/Query/ItemFromCustom.cs, Dynamo13/pkg.json, Dynamo20/Dynamo_Engine/Convert/FromDesignScript.cs, Dynamo20/Dynamo_Engine/Convert/ToBHoM.cs, Dynamo20/Dynamo_Engine/Convert/ToTargetType.cs, Dynamo20/Dynamo_Engine/Dynamo20_Engine.csproj, Dynamo20/Dynamo_Engine/Objects/DataAccessor_Dynamo.cs, Dynamo20/Dynamo_Engine/Query/Item.cs, Dynamo20/Dynamo_Engine/Query/ItemFromCustom.cs, Dynamo20/pkg.json
Closes #216
Closes #215 
I took the opportunity to also close another compliance issue regarding the content of the pkg file
=> Compliance issues

Dynamo20/Dynamo_Engine/Convert/ToDesignScript.cs
Closes #136
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue136%2DPolylineConvert&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
I am opening this PR to close the subject of curve converts before moving on to other issues. This PR should be a safe one because Dynamo `Polygon` inherits from `PolyCurve`.
=> Conversion of closed BHoM Polyline to Polygon implemented

Dynamo20/Dynamo_Engine/Convert/FromDesignScript.cs
Closes #260 
See issue
If you are struggling to find a simple and reliable way to generate a null, here's an easy one:
=> Fix Crash when exploding a null

Dynamo20/Dynamo_Engine/Compute/RunCaller.cs, Dynamo20/Dynamo_Engine/Convert/FromDesignScript.cs, Dynamo20/Dynamo_Engine/Convert/ToDesignScript.cs, Dynamo20/Dynamo_Engine/Convert/ToPortData.cs, Dynamo20/Dynamo_Engine/Dynamo20_Engine.csproj, Dynamo20/Dynamo_Engine/Objects/DataAccessor_Dynamo.cs, Dynamo20/Dynamo_UI/Global/Extention.cs
https://github.com/BHoM/BHoM/pull/1339
https://github.com/BHoM/BHoM_Engine/pull/2729
https://github.com/BHoM/BHoM_Adapter/pull/318
=> Align with changes in oM and Engine on Reflection -> Base

Dynamo20/Dynamo_Engine/Properties/AssemblyInfo.cs, Dynamo20/Dynamo_UI/Properties/AssemblyInfo.cs
Update Assembly Information to include description
=> Update Assembly Information
